### ISSUE TITLE
Can I merely change the accent color (green) to something else?

### ISSUE THREAD

**Issue by smlombardi** [atom/one-light-ui#31]
I'm not particularly fond of green.  :smile: 

Can I override it in my style sheet?

**Comment by simurai** [comment]
What's the syntax theme you're using? The accent color is based on the background of the syntax theme. If the background is pure white, the accent color defaults to a blueish `#4777D7`.

There isn't an easy way to change the accent variable, but you could try to override all places where the accent color is used. Something like:

```less
@my-accent-color: red;

.tab-bar .tab::before,
.tree-view::before {
  background-color: @my-accent-color;
}
atom-text-editor[mini].is-focused {
  border-color: @my-accent-color;
  box-shadow: 0 0 0 1px @my-accent-color;
  background-color: lighten(@my-accent-color, 44%);
}
```
