### ISSUE TITLE
Top border is fat on OS X

### ISSUE THREAD

**Issue by yuriihabrusiev** [atom/one-light-ui#53]
<img width="1016" alt="screenshot 2016-03-18 11 19 34" src="https://cloud.githubusercontent.com/assets/901000/13873662/8e4eba02-ecfb-11e5-9646-610a69059081.png">

In [styles/atom.less](https://github.com/atom/one-light-ui/blob/master/styles/atom.less#L18) we have
```less
.platform-darwin {
	atom-workspace.theme-one-light-ui {
	  border-top: 1px solid darken(@base-border-color, 20%);
	}
	&.is-blurred atom-workspace.theme-one-light-ui {
	  border-top-color: @base-border-color;
	}
}
```

If disable this via DevTools:
<img width="993" alt="screenshot 2016-03-18 11 24 50" src="https://cloud.githubusercontent.com/assets/901000/13873743/2b5511ac-ecfc-11e5-80dc-c0b5e3af9f3f.png">

One Dark also has this code but border is not visible because you used exactly [same code](https://github.com/atom/one-dark-ui/blob/master/styles/atom.less#L19) :smiley:
