### ISSUE TITLE
Adjusting the font-size does not adjust the tree font/icon size

### ISSUE THREAD

**Issue by mickyginger** [atom/one-light-ui#74]
It would be great if the tree font size would link up to the cmd+/cmd- keys, so that one could change the font-size globally across the theme. Similar to this https://github.com/atom/atom/issues/11905#issuecomment-225068527

**Comment by simurai** [comment]
You could try 

```less
.icon:before {
  font-size: inherit !important;
  width: initial !important;
  height: initial !important;
}
```

to keep the icons tied to the font-size. Although they look sharpest with `16px, 32px, 48px, etc`. Not an issue on retina screens though.
