### ISSUE TITLE
 ui-variable to set the tree view line height

### ISSUE THREAD

**Issue by svoop** [atom/one-light-ui#9]
This theme is really great!

Would it be possible to add a ui-variable or a setting to decrease the line height in the tree view? There's a lot of whitespace between the lines which renders the tree view less useful than it could be.

![a9eb5f48-aeba-11e4-9b11-cedafeef1d49](https://cloud.githubusercontent.com/assets/7255/6102518/458668ca-b038-11e4-80fb-1b1facd29f62.png)

**Comment by simurai** [comment]
@svoop There is the `@component-line-height` that could be changed: https://github.com/atom/one-light-ui/blob/master/styles/ui-variables.less#L159 But if you change it locally, the next time the theme updates, it will be overridden again.

Instead you could override it in your `syles.less` file. Something like this:

```less

// Make tree-view more compact
.tree-view {
  .list-group li:not(.list-nested-item),
  .list-tree li:not(.list-nested-item),
  .list-group li.list-nested-item > .list-item,
  .list-tree li.list-nested-item > .list-item {
    line-height: 20px;
  }
  .list-group .selected:before,
  .list-tree .selected:before {
    height: 20px;
  }
}
```

Kinda crazy selectors :see_no_evil: , but should work.
